version: '3'

services:
  storage:
    image: quay.io/minio/minio
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    ports:
      - target: 9000
        published: 9000
        protocol: tcp
      - target: 9001
        published: 9001
        protocol: tcp
    volumes:
      - type: volume
        source: data
        target: /data

volumes:
  data: {}